voxpupuli/puppet-extlib

README.markdown
lib/puppet/parser/functions/cache_data.rb
spec/functions/cache_data_spec.rb
spec/spec_helper.rb

Allows retrieving data from a cache file, or creates it with
supplied data if the file doesn't exist. This is useful for having
data that's randomly generated once on the master side (e.g. a password),
but then stays the same on subsequent runs.

Adds cache_data function for caching values on the master

---

lib/puppet/parser/functions/default_content.rb

Wonder if you can be interested in merging this function, currently placed in https://github.com/stdmod/stdmod (a general module whose function is similar to extlib).
Wonder also if you are open to other similar contributions and eventually to the idea of merging the (partly similar) efforts of puppetcommunity and stdmod github orgs.
Usage example for the function:
```puppet
$config_file_template     = undef,
$config_file_content      = undef,
$real_config_file_content = default_content($config_file_content, $config_file_template)
```

Add default_content function

---

.sync.yml
Gemfile
Rakefile

remove Gemfile from sync for now, for we are using the latest (yet
unreleased) version of puppet-blacksmith. This version has
`module:bump:full` which allows us to fully specify the version, so no
more "manual" fiddling.
This version of travis_release also *rejects* releases that are RCs

feat (release) more solid way to release (thru travis)

---

Gemfile
README.markdown
lib/puppet/parser/functions/resources_deep_merge.rb
metadata.json
spec/functions/resources_deep_merge_spec.rb
spec/spec_helper.rb

ax copyright where it exists, since vox pupuli is not an entity yet

rename puppet[ -]?community -> voxpupuli

---

lib/puppet/parser/functions/dump_args.rb
spec/unit/puppet/parser/functions/dump_args_spec.rb

This adds a new function that outputs the variables to STDOUT.  Its pretty dead simple and when used with an rspec test it can decrease debug time greatly. The only other option is to use a bunch of notify resources which to me is not as fast and does not display the variables correctly when you have hashes and arrays in your variables.  If you think this is not useful imagine storing a large hash in hiera and wanting to know why your custom parser is blowing up on your data and the notify statement does a poor job of displaying your 50 line data hash.  Its really nice to see whats in your puppet variables and this helps immensely.
Another use case is trying to find out why create_resources isn't working as expected because your data being passed in is all wrong.
Basically it works like …

Added dump_args statement function for debugging puppet code

---

.rubocop.yml
.travis.yml
CONTRIBUTING.md
Gemfile

See https://github.com/voxpupuli/modulesync_config/pull/93
This commit updates the module to our latest modulesync configuration.

Pin rake to avoid rubocop/rake 11 incompatibility

---

spec/unit/puppet/parser/functions/cache_data_spec.rb
spec/unit/puppet/parser/functions/default_content_spec.rb
spec/unit/puppet/parser/functions/dump_args_spec.rb
spec/unit/puppet/parser/functions/echo_spec.rb
spec/unit/puppet/parser/functions/ip_to_cron_spec.rb
spec/unit/puppet/parser/functions/random_password_spec.rb
spec/unit/puppet/parser/functions/resources_deep_merge_spec.rb

Moved all function spec tests to spec/unit/puppet/parser/functions
Added `type: :puppet_function` as required.  See
https://github.com/rodjek/rspec-puppet#example-groups
Closes #60

Move function spec tests

---

metadata.json

I noticed this because my dependency resolver barfed on it

Fix stdlib version requirement in metadata

---

README.md
REFERENCE.md
lib/puppet/functions/extlib/has_module.rb
spec/functions/has_module_spec.rb

The idea is we can use this to do things like...
```puppet
if extlib::has_module('camptocamp/systemd') {
include systemd
systemd::unit_file { 'some.service':
...
}
} else 
{
}

Add has_module function

---

REFERENCE.md
lib/puppet/functions/default_content.rb

Puppet strings was exploding when trying to generate markdown.
`bundle exec rake strings:generate\[',,,,false,true']`
```
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
(erb):53:in `block (2 levels) in render'
(erb):50:in `each'
(erb):50:in `block in render'
(erb):21:in `each'
(erb):21:in `render'
/home/alex/.rvm/gems/ruby-2.4.1/gems/puppet-strings-2.1.0/lib/puppet-strings/markdown/base.rb:167:in `render'
```
Fixing the `@params` tags fixed this.
The `@summary` tag needing fixing too. `@example` still doesn't work.
Looks like we're hitting https://tickets.puppetlabs.com/browse/PDOC-263

Fix default_content puppet-strings tags

---

spec/classes/coverage_spec.rb

This is now done by rspec-puppet itself.

Remove coverage

---

REFERENCE.md
functions/path_join.pp

The recently released Puppet Strings 2.2 parses `@example` and so this
function needed a small cleanup to improve the outputted `REFERENCE.md`

Improve `extlib::path_join` docs formatting

---

REFERENCE.md
lib/puppet/functions/extlib/read_url.rb
spec/functions/extlib/read_url_spec.rb

I knocked this together to solve a use-case presented on the slack channel.  The user wanted to use `inline_tempate` with a template from a URL (as opposed to one stored in a module).
What could possibly go wrong...
ok.  So I wouldn't recommend trying to read anything other than 'small' files.
I'd also recommend doing something in the calling puppet to give you confidence you've not been returned junk.
Maybe someone will want to add some extra parameters in the future.  Some sort of timeout would probably be a good idea.

Add experimental `extlib::read_url` function

---

lib/facter/puppet_config.rb

As mentioned by @vchepkov in https://github.com/voxpupuli/puppet-extlib/pull/143#discussion_r371002507 `  confine kernel: 'Linux'` is not required

puppet_config: no need to confine to linux

---

.sync.yml
Rakefile

cb774c01d0bed59a88a9e5785d1afff8a4b8b786 removed the deprecated functions which means it's no longer needed to add this override.

Remove strings patterns

---

REFERENCE.md
functions/path_join.pp

It takes an array of strings, not multiple string arguments.

path_join: fix examples

---

functions/dir_clean.pp
functions/dir_split.pp
functions/path_join.pp
spec/functions/extlib/dir_clean_spec.rb

I went down a bit of a rabbit whole looking at simplifying the dir_split function and have created a new function to normalise paths and used it to i simplify the path_join and dir_split functions.  however i am not that familiar with windows so not sure if i have got everything correct, spec test pass and thats about as far as i can go.
I till need to write spec test for the new function but i thought i would send this PR now to see if there is any early feedback.  also i wonder if we should rename these functions under the same name space e.g.
* `extlib::dir::join`
* `extlib::dir::clean`
* `extlib::dir::split`
or `extlib::path::*`

new function dir_clean and refactor

---

lib/facter/extlib__puppet_config.rb
spec/unit/facter/extlib__puppet_config_spec.rb

Early versions of Facter 4 supported creating structured facts by
aggregating multiple dotted facts.
ie `extlib.puppet_config` would become the `puppet_config` key of a top
level structured fact `extlib`.
This behaviour caused too many issues with the existing ecosystem so was
removed in https://github.com/puppetlabs/facter/pull/2339
namespacing for facts might still return.
Quoting @gimmyxd on slack...
```
currently there is no way to switch the auto conversion per fact.  We
are still working on finding the best mechanism to allow enabling dotted
structured facts and ensure a smooth transition from Facter 3 to this
new behaviour: https://tickets.puppetlabs.com/browse/FACT-3000
```

Remove namespaced `extlib.puppet_config` fact

---

REFERENCE.md
lib/puppet/functions/extlib/dump_params.rb
spec/functions/extlib/dump_params_spec.rb

I often find my self wrinting classes where parameters are mapped directly
into a config file e.g.
```puppet
class 'foobar' (
$log_dir = '/var/logs/foobar',
$user    = 'foobar'
) {
file { $log_dir:
ensure => directory,
}
user { $user:
ensure => present,
}
config => {
'log_dir' => $log_dir,
'user'    => $user,
}
file { '/etc/foobar/yaml':
ensure => file,
content => $config.to_yaml,
}
}
```
This new function allows us to simplify the content generation of the
config file using e.g.
```puppet
file { '/etc/foobar/yaml':
ensure => file,
content => extlib::dump_params.to_yaml,
}
```
This is also useful to pass values from a profile to a class e.g.
```puppet
class profile::apache (
$docroot = '/srv/www',
$group   = 'www-data',
) {
class { 'apache':
* => extlib::dump_params
}
}
```
Real world …

extlib::dump_params: Return the parameters pass to the current resource

---

CHANGELOG.md
metadata.json

This is a major release due to dropping support for puppet 5

6.0.0: prepare new release

---

lib/puppet/functions/extlib/to_ini.rb
spec/functions/extlib/to_ini_spec.rb

Based on / copied from:
https://github.com/mmckinst/puppet-hash2stuff/blob/master/lib/puppet/parser/functions/hash2ini.rb
The original author, @mmckinst, claims to have haulted support for this
code and has stated no objection to this function being migrated to
extlib:
https://github.com/mmckinst/puppet-hash2stuff/issues/19
The original hash2ini() function was rejected from stdlib:
https://github.com/puppetlabs/puppetlabs-stdlib/pull/620

RFC: add extlib::to_ini() function

---

REFERENCE.md
lib/puppet/functions/extlib/compare_ip.rb
spec/functions/extlib/compare_ip_spec.rb

This function is to be used with the built-in `sort()` function.

Add `extlib::compare_ip()` function

---

lib/facter/extlib__puppet_config.rb
spec/unit/facter/extlib__puppet_config_spec.rb

```json
{
"extlib__puppet_config": {
"master": {
"localcacert": "/etc/puppetlabs/puppet/ssl/certs/ca.pem",
"ssldir": "/etc/puppetlabs/puppet/ssl"
},
"main": {
"hostpubkey": "/etc/puppetlabs/puppet/ssl/public_keys/puppet.local.pem",
"hostprivkey": "/etc/puppetlabs/puppet/ssl/private_keys/puppet.local.pem",
"hostcert": "/etc/puppetlabs/puppet/ssl/certs/puppet.local.pem",
"localcacert": "/etc/puppetlabs/puppet/ssl/certs/ca.pem",
"ssldir": "/etc/puppetlabs/puppet/ssl",
"vardir": "/opt/puppetlabs/puppet/cache",
"server": "puppet.local",
"environment": "production"
},
"agent": {
"environment": "production"
}
}
}
```

extlib__puppet_config: Add environment settings

---

.sync.yml
Gemfile
REFERENCE.md
lib/puppet/functions/extlib/remote_pql_query.rb
spec/functions/extlib/remote_pql_query_spec.rb

Perform a PuppetDB query on an arbitrary PuppetDB server
If you need to query a PuppetDB server that is not connected to your Puppet Server, (perhaps part of a separate Puppet installation that uses its own PKI), then this function is for you!

Add `remote_pql_query` function

---

REFERENCE.md
functions/remove_blank_lines.pp
spec/functions/remove_blank_lines_spec.rb

This functions removes all blan lines from a block of text e.g
input = ```
foo
bar
foobar
```
output=```
foo
bar
foobar
```
edit: renamed from `clean_blank_lines` to `remove_blank_lines` but open to better names

clean_blank_lines: Add a new function to clean blank Lines

---

lib/facter/extlib__puppet_config.rb
spec/unit/facter/extlib__puppet_config_spec.rb

Add the puppet config directory to the fact.  This will allow folks to more easily find the puppet config directory for adding/tweaking/etc elements along side the puppet configuration.

Add `confdir` to extlib__puppet_config

---

lib/puppet/functions/extlib/remove_resource.rb

The previous implementation used to find the resource in the catalog was causing the following style of error on the Puppetserver.
```
Server Error: Evaluation Error: Error while evaluating a Function Call, Could not autoload puppet/type/file_line: Attempt to redefine entity 'http://puppet.com/2016.1/runtime/type/file_line'
```
This only occurred the first time trying to compile the catalog. Subsequent runs against the same puppetserver would work fine.  I don't fully understand what was causing the type to be reloaded, and this was only an issue if `generate types` had been used to create the `.resource_types/*.pp` metadata file for the type. Presumably puppet is upset when it tries to load the ruby definition of a type after it's already loaded the pcore version??
In this commit, we …

Fix `remove_resource` `Attempt to redefine entity`
