voxpupuli/puppet-extlib

.travis.yml
Gemfile

test for strict-variables and future parser compatibility

test more puppet versions

---

.travis.yml

further distill matrix, following @camptocamp's example

---

Rakefile
spec/no_duplicate.rb

We don't want to duplicate a function in stdlib. Check for that.

Check functions against stdlib

---

README.markdown

There's a pair of typos in the readme file I wished to have updated.

fixing 2 typos that bugged me in the readme

---

Rakefile

our travis_release task now creates an rc version.
This way, the master branch will always have a version that will make it
clear to our users that it's not released. It will never conflict with
a released version, and will always compare smaller than its actual
release (1.2.3-pre < 1.2.3).
This also hides the module:* tasks until they are actually used by the
travis_release task.
Further, module:tag is executed idempotently

feat (release) travis_release now creates -rc version

---

CHANGELOG.md

prep 0.10.4 release

---

README.markdown
lib/puppet/parser/functions/default_content.rb

docs (default_content) align rdoc and readme

---

README.markdown
lib/puppet/parser/functions/default_content.rb
spec/functions/default_content_spec.rb

this also adds tests for default_content!

fix(default_content) don't call template() on empty template_name

---

.sync.yml

Experiment is (successfully) over.

chore(sync) ensure Rakefile and Gemfile are msynced

---

lib/puppet/parser/functions/ip_to_cron.rb
spec/unit/puppet/parser/functions/dump_args_spec.rb
spec/unit/puppet/parser/functions/ip_to_cron_spec.rb

Fixes GH-48: Import ip_to_cron.rb from theforeman/puppet-puppet

---

CHANGELOG.md
metadata.json

Release 0.11.1

---

lib/puppet/parser/functions/ip_to_cron.rb
spec/spec_helper.rb
spec/unit/puppet/parser/functions/cache_data_spec.rb
spec/unit/puppet/parser/functions/ip_to_cron_spec.rb

Add better ip_to_cron unit tests

---

.msync.yml
.rubocop.yml
.travis.yml
CHANGELOG.md
Gemfile
Rakefile
lib/puppet/parser/functions/default_content.rb
lib/puppet/parser/functions/dump_args.rb
metadata.json

modulesync 0.12.2 & Release 1.0.0

---

.gitignore
.msync.yml
.rubocop.yml
.sync.yml
Gemfile
lib/puppet/parser/functions/random_password.rb
spec/acceptance/nodesets/docker/centos-5.yml
spec/acceptance/nodesets/docker/centos-6.yml
spec/acceptance/nodesets/docker/centos-7.yml
spec/acceptance/nodesets/docker/debian-7.yml
spec/acceptance/nodesets/docker/debian-8.yml
spec/acceptance/nodesets/docker/ubuntu-12.04.yml
spec/acceptance/nodesets/docker/ubuntu-14.04.yml
spec/acceptance/nodesets/docker/ubuntu-16.04.yml
spec/spec_helper.rb
spec/spec_helper_methods.rb

modulesync 0.15.0

---

.github/CONTRIBUTING.md
.gitignore
.msync.yml
.overcommit.yml
.rspec_parallel
.rubocop.yml
.travis.yml
Gemfile
Guardfile
lib/puppet/parser/functions/random_password.rb
spec/acceptance/nodesets/archlinux-2-x64.yml
spec/acceptance/nodesets/docker/ubuntu-16.04.yml
spec/unit/puppet/parser/functions/echo_spec.rb
spec/unit/puppet/parser/functions/ip_to_cron_spec.rb

Modulesync 0.21.3

---

CHANGELOG.md
metadata.json

release 2.3.1

---

REFERENCE.md
lib/puppet/functions/default_content.rb

This is essentially the same, but easier to read.

Use Optional[String] in default_content()

---

README.md
REFERENCE.md
lib/puppet/functions/extlib/default_content.rb
lib/puppet/functions/extlib/has_module.rb
lib/puppet/functions/extlib/sort_by_version.rb
metadata.json

* Clean up README.md
* Regenerate REFERENCE.md without deprecated functions.

Clean up documentation

---

.sync.yml
README.md

Relies on https://github.com/voxpupuli/modulesync_config/pull/543

Use the new rake reference task

---

.sync.yml
README.md
REFERENCE.md
Rakefile
functions/dir_split.pp
functions/file_separator.pp
functions/mkdir_p.pp
functions/path_join.pp
spec/functions/extlib/dir_split_spec.rb
spec/functions/extlib/file_separator_spec.rb
spec/functions/extlib/mkdir_p_spec.rb
spec/functions/extlib/path_join_spec.rb

The main goal was to create a mkdir_p function.  However, this also required some other functions to support the goal so I added those functions as well. 
* path_join()
* file_separator()
* dir_split()
* mkdir_p()
path_join is probably going to be a popular function as it also takes a windows path and turns it into unix form in addition to just joining parts of a path together by the separator.  The path join function should make for better multi platform path manipulation.

Add new file based functions

---

README.md
REFERENCE.md
lib/facter/puppet_config.rb
spec/unit/facter/puppet_settings.rb

This new fact aims to expose some of the configurations parameters of
puppet.  it is similar to the puppet_settings fact in stdlib but uses
structured facts and exposes a few more settings.
I first attempted to submit something similar to stdlib[1] but got
redirected here.  happy to update if this is useful or abandon if not
[1]https://github.com/puppetlabs/puppetlabs-stdlib/pull/1063

This PR adds a new fact puppet_config

---

CHANGELOG.md
lib/facter/puppet_config.rb
metadata.json

 release 4.2.0

---

metadata.json

mark Ubuntu 20.04 as supported

---

.gitignore
.sync.yml
functions/dir_split.pp
functions/mkdir_p.pp
spec/functions/extlib/cache_data_spec.rb
spec/spec_helper.rb
spec/spec_helper_methods.rb

These do not appear to be needed anymore. Removing this simplifies the code.

Remove cache_data helper methods

---

REFERENCE.md
lib/puppet/functions/extlib/cidr_to_netmask.rb
spec/functions/extlib/cidr_to_netmask.rb

Add cidr_to_netmask function

---

REFERENCE.md
lib/puppet/functions/extlib/last_in_cidr.rb
spec/functions/extlib/last_in_cidr.rb

Add last_in_cidr function

---

REFERENCE.md
lib/puppet/functions/extlib/cidr_to_network.rb
spec/functions/extlib/cidr_to_network.rb

Add cidr_to_network function

---

.editorconfig
.github/CONTRIBUTING.md
.github/workflows/ci.yml
.github/workflows/release.yml
.gitignore
.msync.yml
.overcommit.yml
.pmtignore
.rspec
.rspec_parallel
.rubocop.yml
.yardopts
Dockerfile
Gemfile
Rakefile
spec/functions/extlib/dir_clean_spec.rb
spec/functions/extlib/dir_split_spec.rb
spec/functions/extlib/mkdir_p_spec.rb
spec/functions/extlib/path_join_spec.rb
spec/spec_helper.rb

Update from voxpupuli modulesync_config

---

.editorconfig
.github/CONTRIBUTING.md
.github/workflows/ci.yml
.github/workflows/release.yml
.gitignore
.msync.yml
.overcommit.yml
.pmtignore
.rspec
.rspec_parallel
.rubocop.yml
.yardopts
Dockerfile
Gemfile
Rakefile
metadata.json
spec/functions/extlib/dir_clean_spec.rb
spec/functions/extlib/dir_split_spec.rb
spec/functions/extlib/mkdir_p_spec.rb
spec/functions/extlib/path_join_spec.rb
spec/spec_helper.rb

Add support for Debian 11

---

metadata.json

Drop EoL RHEL/CentOS 6 support

---

metadata.json

Drop EoL Debian 8/9

---

CHANGELOG.md
REFERENCE.md
metadata.json

release 6.2.0
